// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EmployeeManagement.Entities
{
    public partial class Branch
    {
        public Branch()
        {
            BranchSubjects = new HashSet<BranchSubjects>();
            Employee = new HashSet<Employee>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }

        public virtual ICollection<BranchSubjects> BranchSubjects { get; set; }
        public virtual ICollection<Employee> Employee { get; set; }
    }
}