// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EmployeeManagement.Entities
{
    public partial class Marks
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int SubjectsId { get; set; }
        public double MarksScored { get; set; }

        public virtual Subjects Subjects { get; set; }
    }
}